dist:
  name: otelcol-influxdb
  module: github.com/influxdata/influxdb-observability/otelcol-influxdb
  description: OpenTelemetry Collector Distribution built for InfluxDB
  version: 0.66.0-0.0.1-beta.0
  otelcol_version: 0.66.0
  output_path: ./build

receivers:
- import: go.opentelemetry.io/collector/receiver/otlpreceiver
  gomod: go.opentelemetry.io/collector v0.66.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.66.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver v0.66.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkametricsreceiver v0.66.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/kafkareceiver v0.66.0

exporters:
- import: go.opentelemetry.io/collector/exporter/otlpexporter
  gomod: go.opentelemetry.io/collector v0.66.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/influxdbexporter v0.66.0

extensions:
- import: go.opentelemetry.io/collector/extension/ballastextension
  gomod: go.opentelemetry.io/collector v0.66.0
- import: go.opentelemetry.io/collector/extension/zpagesextension
  gomod: go.opentelemetry.io/collector v0.66.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/bearertokenauthextension v0.66.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/headerssetterextension v0.66.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.66.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.66.0

processors:
- import: go.opentelemetry.io/collector/processor/batchprocessor
  gomod: go.opentelemetry.io/collector v0.66.0
- import: go.opentelemetry.io/collector/processor/memorylimiterprocessor
  gomod: go.opentelemetry.io/collector v0.66.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/probabilisticsamplerprocessor v0.66.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/routingprocessor v0.66.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanmetricsprocessor v0.66.0
- gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/tailsamplingprocessor v0.66.0

replaces:
- github.com/influxdata/influxdb-observability/common => ../../common
- github.com/influxdata/influxdb-observability/influx2otel => ../../influx2otel
- github.com/influxdata/influxdb-observability/otel2influx => ../../otel2influx
- github.com/open-telemetry/opentelemetry-collector-contrib/exporter/influxdbexporter => ../influxdbexporter
- cloud.google.com/go => cloud.google.com/go v0.106.0
