{
 "title": "Otel Demo",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": "redis" },
   { "name": "traceid", "query": "529942d8b8005150" }
  ]
 },
 "panels": [
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT distinct(\"service.name\") FROM iox.spans WHERE time >= $__timeFrom AND time <= $__timeTo "
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  (COUNT(CASE WHEN \"otel.status_code\" = 'Error' THEN 1 END) * 100.0) / COUNT(*) as error_percentage, \"service.name\" FROM spans\n  WHERE time >= $__timeFrom AND time <= $__timeTo GROUP BY \"service.name\""
    }
   ]
  },
  {
   "title": "Service TraceID Duration",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 8 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"duration_nano\"/ 1000000 as \"duration\", \"trace_id\", time FROM iox.spans WHERE time >= $__timeFrom AND time <= $__timeTo order by time"
    }
   ]
  },
  {
   "title": "Trace Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 17 },
   "targets": [
    { "service": "$service" }
   ]
  },
  {
   "title": "Span Tree ",
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 17 },
   "targets": [
    { "query": "$traceid" }
   ]
  },
  {
   "title": "Trace View",
   "type": "traces",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "targets": [
    { "query": "$traceid" }
   ]
  }
 ]
}