receivers:
  jaeger:
    protocols:
      thrift_compact:
      thrift_http:

  otlp:
    protocols:
      grpc:
      http:

exporters:
  influxdb:
    endpoint: https://${INFLUXDB_ADDR}/
    bucket: ${INFLUXDB_BUCKET}
    token: ${INFLUXDB_TOKEN}
    metrics_schema: otel-v1

service:
  telemetry:
    logs:
      level: debug
      encoding: json

  pipelines:
    traces:
      receivers: [otlp, jaeger]
      exporters: [influxdb]
