receivers:
  jaeger:
    protocols:
      thrift_compact:
      thrift_http:

  otlp:
    protocols:
      grpc:
      http:

exporters:
  influxdb:
    endpoint:
    bucket: otel
    token:

service:
  telemetry:
    logs:
      level: debug
      encoding: json

  pipelines:
    traces:
      receivers: [otlp, jaeger]
      processors: [spanmetrics]
      exporters: [influxdb]
